// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/remotehy/go-std-mod/app/tom/business"
	"github.com/remotehy/go-std-mod/app/tom/data"
	"github.com/remotehy/go-std-mod/app/tom/service"
	"os"
)

// Injectors from wire.go:

func NewService() service.Service {
	baz := _wireBazValue
	string2 := baz.MyStr
	reader := _wireFileValue
	dataAccessImpl := data.NewData(string2, reader)
	businessImpl := business.NewBusiness(dataAccessImpl)
	foo := _wireFooValue
	bar := _wireBarValue
	myThinger := service.MyThinger{
		MyFoo: foo,
		MyBar: bar,
	}
	serviceImpl := service.NewService(businessImpl, myThinger)
	return serviceImpl
}

var (
	_wireBazValue  = data.Baz{MyStr: "hello"}
	_wireFileValue = os.Stdin
	_wireFooValue  = service.Foo(1)
	_wireBarValue  = service.Bar("hello")
)
